package com.drawit.drawit.dto;


import com.drawit.drawit.enums.GameStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * game response send back to fe
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class GameResponseDto {
    private Long gameId;
    private String gameCode;
    private List<String> words; // list words generated by AI or get from db
    private String playerSessionId;
    private GameStatus status;
    private String theme;
    private Integer maxRounds;
    private Integer currentRound;
    private Integer currentTurnNumber; // start by 0
    private Integer drawingTime;
    private Integer guessingTime;
    private Boolean isHost;
    private List<PlayerDto> players;
    private String currentDrawerSessionId; // TODO drawer, missed guesser
}
