name: "Build and deploy draw-it app to server"

on:
  push:
    branches:
      - feature/publish-app-1st

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.ONLINE_HOST }} # ip of server
          username: ${{ secrets.ONLINE_USERNAME }} # Username to login to server
          key: ${{ secrets.ONLINE_SSH_PRIVATE_KEY }} # Private key to login to server
          script: |
            set -e

            cd ${{ secrets.ONLINE_PATH_PROJECT }} 

            if [ -d draw-it-app ]; then
              cd draw-it-app
              git fetch 
              git pull
            else
              git clone -b feature/publish-app-1st git@github.com:astropop/draw-it-app.git
              cd draw-it-app
            fi

            cd ${{ secrets.ONLINE_PATH_PROJECT }}/draw-it-app/draw-it-frontend

            docker compose build
            docker compose up -d --remove-orphans
            docker image prune -f

            cd ${{ secrets.ONLINE_PATH_PROJECT }}/draw-it-app/draw-it-backend

            echo "DRAWIT_DB_URL=${{ secrets.DRAWIT_DB_URL }}"

            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" > .env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
            echo "REDIS_PASS=${{ secrets.REDIS_PASS }}" >> .env
            echo "DRAWIT_HUGGINGFACE_TK=${{ secrets.DRAWIT_HUGGINGFACE_TK }}" >> .env
            echo "DRAWIT_DB_SCHEMA=${{ secrets.DRAWIT_DB_SCHEMA }}" >> .env
            echo "DRAWIT_DB_URL=${{ secrets.DRAWIT_DB_URL }}" >> .env
            echo "DRAWIT_DB_PORT=${{ secrets.DRAWIT_DB_PORT }}" >> .env
            echo "DRAWIT_DB_USER=${{ secrets.DRAWIT_DB_USER }}" >> .env
            echo "DRAWIT_DB_PASS=${{ secrets.DRAWIT_DB_PASS }}" >> .env

            cat .env

            docker compose build
            docker compose up -d --remove-orphans
            docker image prune -f
