name: "Build and deploy draw-it app to server"

on:
  push:
    branches:
      - feature/publish-app-1st

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASS: ${{ secrets.REDIS_PASS }}
      DRAWIT_HUGGINGFACE_TK: ${{ secrets.DRAWIT_HUGGINGFACE_TK }}
      DRAWIT_DB_SCHEMA: ${{ secrets.DRAWIT_DB_SCHEMA }}
      DRAWIT_DB_URL: ${{ secrets.DRAWIT_DB_URL }}
      DRAWIT_DB_PORT: ${{ secrets.DRAWIT_DB_PORT }}
      DRAWIT_DB_USER: ${{ secrets.DRAWIT_DB_USER }}
      DRAWIT_DB_PASS: ${{ secrets.DRAWIT_DB_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.ONLINE_HOST }} # ip of server
          username: ${{ secrets.ONLINE_USERNAME }} # Username to login to server
          key: ${{ secrets.ONLINE_SSH_PRIVATE_KEY }} # Private key to login to server

          script: |
            set -e

            docker container stop draw-it-frontend || true
            docker container stop draw-it-backend || true
            docker container stop my-redis || true

            docker container remove draw-it-frontend || true
            docker container remove draw-it-backend || true
            docker container remove my-redis || true

            docker image remove draw-it-frontend/draw-it-frontend:latest || true
            docker image remove draw-it-backend/draw-it-backend:latest || true
            docker image remove redis:alpine || true
            cd ${{ secrets.ONLINE_PATH_PROJECT }} 

            if [ -d draw-it-app ]; then
              cd draw-it-app
              git fetch 
              git pull
            else
              git clone -b feature/publish-app-1st git@github.com:astropop/draw-it-app.git
              cd draw-it-app
            fi

            cd draw-it-frontend

            docker compose build
            docker compose up -d

            cd ${{ secrets.ONLINE_PATH_PROJECT }}/draw-it-app/draw-it-backend

            docker compose build
            docker compose up -d
